insert into public.motorcycles (
  id, brand, model, year, slug, price, promo_price, category, engine_cc,
  monthly_from, suggested_down_payment, short_description, priority_score,
  available_cities, tags, best_for, specs, image_url, gallery_urls, published
)
values
(
  'yamaha-fz-s-2025',
  'Yamaha',
  'FZ-S',
  2025,
  'fz-s-2025',
  67999,
  null,
  'Ciudad',
  149,
  2350,
  14000,
  'Una naked urbana equilibrada para moverte diario con buen rendimiento y estilo.',
  98,
  $cities$["CDMX","Estado de México","Toluca","Puebla","Querétaro","Cuernavaca"]$cities$::jsonb,
  $tags$["Bajo consumo","Primera moto","Ciudad"]$tags$::jsonb,
  $best$["Traslados diarios","Primera moto","Uso urbano"]$best$::jsonb,
  $specs${"Motor":"149 cc","Transmisión":"5 velocidades","Frenos":"Disco delantero","Uso":"Ciudad"}$specs$::jsonb,
  null,
  $gal$[]$gal$::jsonb,
  true
),
(
  'yamaha-xtz-150-2025',
  'Yamaha',
  'XTZ 150',
  2025,
  'xtz-150-2025',
  82999,
  null,
  'Doble propósito',
  149,
  2850,
  17000,
  'Moto versátil para ciudad, trabajo y caminos irregulares.',
  96,
  $cities$["CDMX","Estado de México","Puebla","Querétaro"]$cities$::jsonb,
  $tags$["Doble propósito","Trabajo","Terracería"]$tags$::jsonb,
  $best$["Reparto","Caminos mixtos","Uso rudo"]$best$::jsonb,
  $specs${"Motor":"149 cc","Transmisión":"5 velocidades","Suspensión":"Largo recorrido","Uso":"Mixto"}$specs$::jsonb,
  null,
  $gal$[]$gal$::jsonb,
  true
),
(
  'bajaj-boxer-150-2025',
  'Bajaj',
  'Boxer 150',
  2025,
  'boxer-150-2025',
  40999,
  null,
  'Trabajo',
  150,
  1550,
  8500,
  'Moto enfocada en trabajo diario, resistencia y bajo costo de uso.',
  95,
  $cities$["CDMX","Estado de México","Toluca","Puebla","Querétaro"]$cities$::jsonb,
  $tags$["Trabajo","Reparto","Económica"]$tags$::jsonb,
  $best$["Delivery","Trabajo diario","Bajo presupuesto"]$best$::jsonb,
  $specs${"Motor":"150 cc","Transmisión":"5 velocidades","Uso":"Trabajo","Enfoque":"Costo operativo"}$specs$::jsonb,
  null,
  $gal$[]$gal$::jsonb,
  true
),
(
  'tvs-raider-125-2025',
  'TVS',
  'Raider 125',
  2025,
  'raider-125-2025',
  48999,
  null,
  'Ciudad',
  125,
  1800,
  10000,
  'Opción urbana ágil para quien busca moverse barato sin perder diseño.',
  94,
  $cities$["CDMX","Estado de México","Toluca","Puebla","Cuernavaca"]$cities$::jsonb,
  $tags$["Ciudad","Económica","Primera moto"]$tags$::jsonb,
  $best$["Primera moto","Traslados diarios","Ahorro"]$best$::jsonb,
  $specs${"Motor":"125 cc","Transmisión":"5 velocidades","Uso":"Ciudad","Enfoque":"Eficiencia"}$specs$::jsonb,
  null,
  $gal$[]$gal$::jsonb,
  true
),
(
  'bajaj-pulsar-ns200-2025',
  'Bajaj',
  'Pulsar NS200',
  2025,
  'pulsar-ns200-2025',
  68999,
  null,
  'Deportiva',
  200,
  2380,
  14000,
  'Naked deportiva con buena relación entre precio, desempeño y presencia.',
  93,
  $cities$["CDMX","Estado de México","Puebla","Querétaro","Cuernavaca"]$cities$::jsonb,
  $tags$["Deportiva","Precio valor","Ciudad"]$tags$::jsonb,
  $best$["Jóvenes","Ciudad","Manejo dinámico"]$best$::jsonb,
  $specs${"Motor":"200 cc","Transmisión":"6 velocidades","Uso":"Ciudad","Enfoque":"Desempeño"}$specs$::jsonb,
  null,
  $gal$[]$gal$::jsonb,
  true
),
(
  'suzuki-gixxer-150-2025',
  'Suzuki',
  'GIXXER 150',
  2025,
  'gixxer-150-2025',
  63999,
  null,
  'Ciudad',
  155,
  2250,
  13000,
  'Naked urbana para uso diario con estilo deportivo y manejo ligero.',
  92,
  $cities$["CDMX","Estado de México","Puebla","Querétaro"]$cities$::jsonb,
  $tags$["Ciudad","Naked","Bajo consumo"]$tags$::jsonb,
  $best$["Uso diario","Primera moto","Ciudad"]$best$::jsonb,
  $specs${"Motor":"155 cc","Transmisión":"5 velocidades","Uso":"Ciudad","Enfoque":"Balance"}$specs$::jsonb,
  null,
  $gal$[]$gal$::jsonb,
  true
),
(
  'tvs-apache-rtr-200-2025',
  'TVS',
  'Apache RTR 200',
  2025,
  'apache-rtr-200-2025',
  72999,
  null,
  'Deportiva',
  200,
  2550,
  15000,
  'Moto de estilo deportivo para quien quiere más respuesta sin subir demasiado de presupuesto.',
  91,
  $cities$["CDMX","Estado de México","Puebla","Querétaro"]$cities$::jsonb,
  $tags$["Deportiva","Naked","Tecnología"]$tags$::jsonb,
  $best$["Ciudad rápida","Manejo divertido","Upgrade"]$best$::jsonb,
  $specs${"Motor":"200 cc","Transmisión":"5 velocidades","Uso":"Ciudad","Enfoque":"Desempeño"}$specs$::jsonb,
  null,
  $gal$[]$gal$::jsonb,
  true
),
(
  'yamaha-nmax-2025',
  'Yamaha',
  'NMAX',
  2025,
  'nmax-2025',
  94999,
  null,
  'Scooter',
  155,
  3200,
  19000,
  'Scooter cómoda, automática y práctica para moverte en ciudad.',
  90,
  $cities$["CDMX","Estado de México","Puebla","Querétaro"]$cities$::jsonb,
  $tags$["Scooter","Automática","Ciudad"]$tags$::jsonb,
  $best$["Ciudad","Comodidad","Manejo automático"]$best$::jsonb,
  $specs${"Motor":"155 cc","Transmisión":"Automática","Frenos":"ABS","Uso":"Ciudad"}$specs$::jsonb,
  null,
  $gal$[]$gal$::jsonb,
  true
),
(
  'suzuki-v-strom-250sx-2025',
  'Suzuki',
  'V-STROM 250SX',
  2025,
  'v-strom-250sx-2025',
  114999,
  null,
  'Doble propósito',
  250,
  3900,
  23000,
  'Moto aventurera ligera para ciudad, carretera y escapadas de fin de semana.',
  88,
  $cities$["CDMX","Estado de México","Puebla","Querétaro"]$cities$::jsonb,
  $tags$["Aventura","Doble propósito","Touring"]$tags$::jsonb,
  $best$["Carretera ligera","Aventura","Uso mixto"]$best$::jsonb,
  $specs${"Motor":"250 cc","Transmisión":"6 velocidades","Uso":"Mixto","Enfoque":"Aventura"}$specs$::jsonb,
  null,
  $gal$[]$gal$::jsonb,
  true
),
(
  'tvs-ntorq-125-2025',
  'TVS',
  'Ntorq 125',
  2025,
  'ntorq-125-2025',
  52999,
  null,
  'Scooter',
  125,
  1950,
  11000,
  'Scooter práctica y juvenil para trayectos urbanos con manejo sencillo.',
  87,
  $cities$["CDMX","Estado de México","Toluca","Puebla"]$cities$::jsonb,
  $tags$["Scooter","Automática","Ciudad"]$tags$::jsonb,
  $best$["Ciudad","Primera scooter","Movilidad diaria"]$best$::jsonb,
  $specs${"Motor":"125 cc","Transmisión":"Automática","Uso":"Ciudad","Enfoque":"Practicidad"}$specs$::jsonb,
  null,
  $gal$[]$gal$::jsonb,
  true
),
(
  'yamaha-mt-03-2025',
  'Yamaha',
  'MT-03',
  2025,
  'mt-03-2025',
  158999,
  null,
  'Deportiva',
  321,
  5200,
  32000,
  'Naked deportiva para quien quiere más potencia, presencia y manejo divertido.',
  86,
  $cities$["CDMX","Estado de México","Querétaro","Puebla"]$cities$::jsonb,
  $tags$["Deportiva","Premium","Naked"]$tags$::jsonb,
  $best$["Manejo deportivo","Ciudad y carretera","Upgrade de cilindrada"]$best$::jsonb,
  $specs${"Motor":"321 cc","Transmisión":"6 velocidades","Frenos":"ABS","Uso":"Ciudad/carretera"}$specs$::jsonb,
  null,
  $gal$[]$gal$::jsonb,
  true
),
(
  'bajaj-dominar-400-2025',
  'Bajaj',
  'Dominar 400',
  2025,
  'dominar-400-2025',
  96999,
  null,
  'Touring',
  400,
  3400,
  20000,
  'Moto de mayor cilindrada para trayectos largos y manejo con más potencia.',
  84,
  $cities$["CDMX","Estado de México","Puebla","Querétaro"]$cities$::jsonb,
  $tags$["Touring","Carretera","Potencia"]$tags$::jsonb,
  $best$["Carretera","Viajes cortos","Upgrade de cilindrada"]$best$::jsonb,
  $specs${"Motor":"400 cc","Transmisión":"6 velocidades","Uso":"Carretera/ciudad","Enfoque":"Potencia"}$specs$::jsonb,
  null,
  $gal$[]$gal$::jsonb,
  true
)
on conflict (id) do update set
  brand = excluded.brand,
  model = excluded.model,
  year = excluded.year,
  slug = excluded.slug,
  price = excluded.price,
  promo_price = excluded.promo_price,
  category = excluded.category,
  engine_cc = excluded.engine_cc,
  monthly_from = excluded.monthly_from,
  suggested_down_payment = excluded.suggested_down_payment,
  short_description = excluded.short_description,
  priority_score = excluded.priority_score,
  available_cities = excluded.available_cities,
  tags = excluded.tags,
  best_for = excluded.best_for,
  specs = excluded.specs,
  image_url = excluded.image_url,
  gallery_urls = excluded.gallery_urls,
  published = excluded.published;

